name: reading-corner-web
run-name: ReadingCorner Web

on:
  push:
    paths:
      - 'frontend/**'
    
concurrency: merge-${{ github.ref }}
    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  checkout-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: false
        
      - name: Get pnpm store directory
        shell: bash
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
  
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-pnpm-store-
  
      - name: Install dependencies
        run: pnpm install

  DeployApp:
    runs-on: ubuntu-latest
    needs: checkout-and-install
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::724538604969:role/Github
          aws-region: ap-southeast-2
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: false
      - name: Deploy app
        run: |
          pnpm sst deploy --stage uat
